Fixed linker error on macOS/OS X 10.9+
I ran into a problem trying to build the project with stack build or
stack install on macOS/OS X version >= 10.9. It spits out this linker
error:
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see
invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

I've added `-stdlib=libstdc++` cpp flag to link against libstdc++
instead of libc++ which is default from OS X version 10.9 up.

Fixes #3291